# Main composition file for TFTP Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

version: '3.8'
services:
  tftpserver:
    container_name: tftpserver
    hostname: tftpserver
    restart: always
    network_mode: "host"
    # Volume mount to share TFTP files:
    volumes:
      - "./data/:/tftpshare"
    # Map container build context to TFTPserver container:
    build:
      context: .
      dockerfile: ./docker/Dockerfile